/**
 * Bundled static fixtures for STATIC_MODE (Vercel demo deploy, no backend).
 *
 * These JSON files are generated by `agentready/scripts/export_static.py`,
 * which runs the real receipts-mode pipeline for all seven brands and writes
 * the exact shapes the frontend consumes. Re-run that script to refresh.
 */

import type { Brand, Scan } from "@/lib/api";
import type { AgentJourneyEvent } from "@/lib/events";

import brandsData from "@/data/brands.json";
import allbirds from "@/data/scans/allbirds.json";
import lululemon from "@/data/scans/lululemon.json";
import mcmaster from "@/data/scans/mcmaster.json";
import owala from "@/data/scans/owala.json";
import pandora from "@/data/scans/pandora.json";
import stanley from "@/data/scans/stanley.json";
import yeti from "@/data/scans/yeti.json";

export type StaticJourney = AgentJourneyEvent["journey"];

export type StaticScanPayload = {
  scan: Scan;
  journeys: StaticJourney[];
  receipts_count: number;
};

export const STATIC_BRANDS = brandsData as unknown as Brand[];

export const STATIC_SCANS: Record<string, StaticScanPayload> = {
  stanley: stanley as unknown as StaticScanPayload,
  yeti: yeti as unknown as StaticScanPayload,
  owala: owala as unknown as StaticScanPayload,
  allbirds: allbirds as unknown as StaticScanPayload,
  lululemon: lululemon as unknown as StaticScanPayload,
  pandora: pandora as unknown as StaticScanPayload,
  mcmaster: mcmaster as unknown as StaticScanPayload,
};
